name: WINDOWS|TESTS
permissions:
  contents: read
  actions: read
  checks: none
  deployments: none
  issues: none
  discussions: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

on: 
  workflow_run:
    workflows: [WINDOWS|BUILD]
    branches: [main]
    types: [completed]

jobs:
  tests:
    name: Tests
    runs-on: windows-2019
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Get event json
        id: get_event_json
        run: |
          $content=cat ${GITHUB_EVENT_PATH}
          content="${content//'%'/''}"
          content="${content//$'\n'/''}"
          content="${content//$'\r'/''}"
          echo "value=${content}" >> ${GITHUB_OUTPUT}

      - name: Get run id
        id: get_run_id
        run: |
          echo "value="${{ fromJson(steps.get_event_json.outputs.value).workflow_run.id }} >> ${GITHUB_OUTPUT}

      - name: Get tests binaries
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ steps.get_run_id.outputs.value }}
          name: tests
          github-token: ${{ secrets.GH_PAT }}

      - run: tar zxvf install.tar.gz

      - run: echo  >> ${GITHUB_OUTPUT}
        id: ldflags

      - run: |
            $LDFLAGS=-L./install/lib
            ./install/bin/tests-details

      - run: |
            $LDFLAGS=-L./install/lib
            ./install/bin/tests-siege
